version: '3'


services:

  frontend:
    container_name:
      frontend-prod
    image: rabwent11/lcapp2:frontend-v1
    environment:
      - "GENERIC_API_URL_FROM_ENV=http://127.0.0.1:5000/"
      - "COMPANY_LOGO_URL=https://www.orxagrid.com/images/logo-03-02-2-250x72.png"
      - "COMPANY_WEBSITE_URL=https://www.orxagrid.com"
    restart: always
    ports:
      - '80:80'


  api:
    container_name:
      api-prod
    image: rabwent11/lcapp2:api-v1
    restart: always  
    ports:
      - '5000:5000'
    environment:
      - "PYTHONUNBUFFERED=1"
      - "BROKER_URL=amqp://rabbitmq:5672"
      - "CELERY_BACKEND=mongo"
      - "MINIO_CONN_STR=minio:9000"
      - "MINIO_USER=user"
      - "MINIO_PW=password"
      - "MINIO_RAW_BUCKET=raw-uploads"
      - "MINIO_CLEANED_BUCKET=cleaned-uploads"
      

  worker:
    container_name:
      worker-prod
    image: rabwent11/lcapp2:api-v1
    restart: always    
    environment:
      - "PYTHONUNBUFFERED=1"
      - "BROKER_URL=amqp://rabbitmq:5672"
      - "CELERY_BACKEND=mongo"
      - "MINIO_CONN_STR=minio:9000"
      - "MINIO_USER=user"
      - "MINIO_PW=password"
      - "MINIO_RAW_BUCKET=raw-uploads"
      - "MINIO_CLEANED_BUCKET=cleaned-uploads"
    command: celery -A tasks worker --loglevel=INFO


  minio:
    container_name:
      object-store-prod
    image: minio/minio:RELEASE.2021-05-27T22-06-31Z
    restart: always   
    volumes:
      - minio_vol_deploy:/data
    environment:
      - 'MINIO_ROOT_USER=user'
      - 'MINIO_ROOT_PASSWORD=password'
    command: server /data


  rabbitmq:
    container_name:
      task-queue-prod    
    image: rabbitmq:3.8.16
    restart: always  


  mongo:
    container_name:
      nosql-db-prod    
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongo_vol_deploy:/data/db


volumes:
  minio_vol_deploy:
  mongo_vol_deploy:

