version: '3'


services:

  frontend:
    container_name:
      frontend-prod
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    environment:
      - "GENERIC_API_URL_FROM_ENV=http://127.0.0.1:5000/"
    restart: always
    ports:
      - '80:80'


  api:
    container_name:
      api-prod    
    build: 
      context: api
      dockerfile: Dockerfile.prod
    restart: always  
    ports:
      - '5000:5000'
    environment:
      - "PYTHONUNBUFFERED=1"
      - "BROKER_URL=amqp://rabbitmq:5672"
      - "CELERY_BACKEND=mongo"
      - "MINIO_CONN_STR=minio:9000"
      - "MINIO_USER=user"
      - "MINIO_PW=password"
      - "MINIO_RAW_BUCKET=raw-uploads"
      - "MINIO_CLEANED_BUCKET=cleaned-uploads"
      - 'BILLING_DB_CONN_STR=host=postgres user=postgres dbname=postgres password=password sslmode=allow'


  worker:
    container_name:
      worker-prod
    build: 
      context: api
      dockerfile: Dockerfile.prod
    restart: always    
    environment:
      - "PYTHONUNBUFFERED=1"
      - "BROKER_URL=amqp://rabbitmq:5672"
      - "CELERY_BACKEND=mongo"
      - "MINIO_CONN_STR=minio:9000"
      - "MINIO_USER=user"
      - "MINIO_PW=password"
      - "MINIO_RAW_BUCKET=raw-uploads"
      - "MINIO_CLEANED_BUCKET=cleaned-uploads"
    command: celery -A tasks worker --loglevel=INFO


  minio:
    container_name:
      object-store-prod
    image: minio/minio:RELEASE.2021-05-27T22-06-31Z
    restart: always   
    volumes:
      - minio_vol_prod:/data
    environment:
      - 'MINIO_ROOT_USER=user'
      - 'MINIO_ROOT_PASSWORD=password'
    command: server /data


  postgres:
    container_name:
      sql-db-prod    
    image: postgres:11
    restart: always  
    environment:
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - ./db/startup_scripts:/docker-entrypoint-initdb.d


  rabbitmq:
    container_name:
      task-queue-prod    
    image: rabbitmq:3.8.16
    restart: always  


  mongo:
    container_name:
      nosql-db-prod    
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongo_vol_prod:/data/db


volumes:
  minio_vol_prod:
  mongo_vol_prod:

