version: '3'

services:

  minio:
    image: minio/minio
    volumes:
      - minio_vol:/data
    ports:
      - '9000:9000'
    # environment:
    #   MINIO_ROOT_USER: root
    #   MINIO_ROOT_PASSWORD: password
    command: server /data


  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - ./db/startup_scripts:/docker-entrypoint-initdb.d


  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'


  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_vol:/data/db


  # api:
  #   build: api
  #   ports:
  #     - '80:5000'
  #   environment:
  #     # - "PYTHONUNBUFFERED=1"
  #     - "MINIO_CONN_STR=minio:9000"
  #     - "MINIO_USER=farms"
  #     - "MINIO_PW=uprooted"
  #     # - "MINIO_SECURE=0"
  #     - "MINIO_PHOTO_BUCKET=photos"
  #     - "MONGO_CONN_STR=mongodb://root:pass@mongo:27017/"
  #     - "PRINT_SERVER_HOST=http://print_server:5005/"
  #     - "ROOT_URL=169.254.0.1:80/"
  #     - "BASIC_AUTH_USERNAME=uprooted"
  #     - "BASIC_AUTH_PASSWORD=farms"
  #   # volumes:
  #   #   - "./api:/app"
    

volumes:
  minio_vol:
  mongo_vol: